### ISSUE TITLE
네트워크 챕터에 다수의 오타가 있습니다

### ISSUE THREAD

**Issue by codingmarine** [kangtegong/cs#2]
![image](https://github.com/user-attachments/assets/d38ac220-10b6-4c8b-a078-033c75ca0a6a)
안녕하세요? 오늘 서점에서 책을 구입해서 잘 보고있는 독자입니다
쪽수가 표기되어야 할 부분에 00쪽, ㅇㅇ쪽 등으로 표시되어 있는데 아마 최종 수정에서 쪽수를 표기하고자 했는데 오타가 난 것이 아닐까 하여 제보 드립니다

그리고 건의사항으로 깃허브나 유튜브 링크를 QR코드로도 인쇄해 주신다면 좀더 접근성이 높아질 것 같습니다

**Comment by kangtegong** [comment]
아.............................
맙소사.......................

우선 말씀해 주셔서 진심으로 감사드리고,
학습에 불편을 드려 정말 죄송합니다.

초판 기준 368 페이지에서 410 페이지까지
조판 오류(페이지 쪽 수 표기 누락)가 있었습니다.

정오표는 다음 링크에 업로드해 두었습니다.

https://github.com/kangtegong/cs/blob/main/etc/corrections.pdf

QR 코드는 정말 좋은 의견입니다.
적극적으로 편집부에 건의해 보겠습니다.

다시 한 번 감사드립니다.
