### ISSUE TITLE
시스템 콜(System Call)과 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by heemanglee** [kangtegong/cs#4]
p.141을 보면 `사용자 모드는 운영체제 서비스를 제공받을 수 없는 실행 모드로, 커널 영역의 코드를 실행할 수 없는 모드입니다.` 라고 작성되어 있습니다. 이부분에 애매하게 와닿는 것 같아 아래 표현과 동일한 것인지 궁금합니다.

`사용자 모드`는 사용자 영역에 적재된 프로그램이므로 직접적으로 시스템 자원을 얻을 수 없다. 반대로 `커널 모드`는 커널 영역에 적재된 운영체제이므로 직접 시스템 자원에 접근하여 응용 프로그램이 필요로 하는 자원을 제공한다.

감사합니다.

**Comment by kangtegong** [comment]
네, 이해하신 것이 맞습니다. 

감사합니다.
강민철 드림
