### ISSUE TITLE
이미지 활용

### ISSUE THREAD

**Issue by dong1728** [kangtegong/cs#8]
안녕하세요~! 조코딩님 유튜브에서 우연히 강민철님이 설명하신 "이것이 컴퓨터 과학이다" 책 내용에대한 설명이 너무 유익해서 서적 구매를 했습니다!
다름 아니라 제가 매일매일 공부한 내용을 제 블로그에 정리하려고 하는데 책에 정리된 이미지를 블로그에 첨부하여 사용해도 되는지 여쭙고 싶어서 Q&A 남기게 되었습니다.
혹시나 저자권법 위반이나 해당 문제가 되지 않도록 작가님한테 허락 받고자 이렇게 글 올리게 되었습니다!

**Comment by kangtegong** [comment]
안녕하세요 좋게 봐주셔서 감사합니다
출처만 남겨주시면 얼마든지 가능합니다
감사합니다^^
